language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install
  - npm install -g mocha jshint grunt-cli
  - wget http://ftp.debian.org/debian/pool/main/l/linkchecker/linkchecker_7.9-2_amd64.deb ; sudo dpkg -i linkchecker_7.9-2_amd64.deb
script:
  - node app.js &
  - grunt
after-script:
  - pkill node
